# Generated by Django 4.2.5 on 2023-09-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='guesses',
            field=models.IntegerField(null=True),
        ),
    ]
