# Generated by Django 4.2.5 on 2023-10-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_random_letter_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='leaderboard',
        ),
    ]
