# Generated by Django 4.2.5 on 2023-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_player_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random_letter',
            name='letter',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
