# Generated by Django 4.2.5 on 2023-10-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='guesses',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
